INSERT INTO options (title, description, poll_id) VALUES
('Chocolate', 'Rich and creamy chocolate flavor.', 1),
('Vanilla', 'Classic and smooth vanilla flavor.', 1),
('Strawberry', 'Sweet and fruity strawberry flavor.', 1),
('The Dark Knight', 'Action-packed superhero film.', 2),
('Avengers: Endgame', 'Epic conclusion to the Avengers saga.', 2),
('Wonder Woman', 'Empowering superhero story.', 2),
('Hawaii', 'Tropical paradise with stunning beaches.', 3),
('Paris', 'Romantic city with iconic landmarks.', 3),
('Tokyo', 'Vibrant metropolis with rich culture.', 3),
('Mystery', 'Intriguing and suspenseful genre.', 4),
('Science Fiction', 'Futuristic and imaginative stories.', 4),
('Fantasy', 'Magical and fantastical worlds.', 4),
('Albert Einstein', 'Developed the theory of relativity.', 5),
('Marie Curie', 'Pioneered research on radioactivity.', 5),
('Isaac Newton', 'Formulated the laws of motion and gravity.', 5),
('Latte', 'Creamy coffee with steamed milk.', 6),
('Cappuccino', 'Bold espresso with frothy milk.', 6),
('Cold Brew', 'Smooth and refreshing iced coffee.', 6),
('Hiking', 'Exploring nature on foot.', 7),
('Camping', 'Enjoying the great outdoors.', 7),
('Cycling', 'Riding a bike for exercise and fun.', 7),
('Monopoly', 'Classic property trading game.', 8),
('Catan', 'Strategic resource management game.', 8),
('Scrabble', 'Word-building and vocabulary game.', 8),
('Breaking Bad', 'Intense crime drama series.', 9),
('Game of Thrones', 'Epic fantasy series.', 9),
('Stranger Things', 'Sci-fi thriller with a nostalgic twist.', 9),
('Dog', 'Loyal and loving canine companion.', 10),
('Cat', 'Independent and curious feline friend.', 10),
('Rabbit', 'Playful and gentle small pet.', 10);
