DROP TABLE IF EXISTS polls CASCADE;
CREATE TABLE polls (
  id SERIAL PRIMARY KEY NOT NULL,
  title VARCHAR(255) NOT NULL,
  admin_id INT NOT NULL,
  poll_link VARCHAR(255),
  admin_link VARCHAR(255),
  FOREIGN KEY (admin_id) REFERENCES users(id)
);
